version: '3.4'

services:
  web:
    image: ${DOCKER_REGISTRY-}bookstoredemo
    build:
      context: .
      dockerfile: Web/Dockerfile
    ports:
      - "5032:80"
    container_name: bookstoredemo
  db:
    image: "mcr.microsoft.com/mssql/server:2017-latest"
    container_name: MyFrameworkDemoDB(bookstoredemo)